PREFIX pokemonkg: <https://pokemonkg.org/ontology#>

# dammi tutti gli oggetti che compaiono nella quadrupla dove il predicato è hasType
SELECT DISTINCT ?tipo
WHERE {
  ?s pokemonkg:hasType ?tipo .
}
